# index - Precipitation

May 2023

### Diana Jaimes

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
import glob
import json
import datetime
from datetime import datetime
import plotly.express as px
import re
from datetime import datetime, date, timedelta
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')

# Datos:

In [3]:
data_file = 'Z:\\1.Data\\Honduras\\landing\\Datos de estaciones\\Precipitacion.xlsx'
precipitacion = pd.read_excel(data_file)
precipitacion

,ESTACION,ESQUIAS,LA ERMITA,SULACO,PLAYITAS,FLORES,PITO SOLO,SANTA ELENA,SANTA ROSA DE COPAN,EL NISPERO,LA UNION,SAN JOSE DE LA MONTAÃ‘A,SANTA RITA,LA ENTRADA,QUIMISTA,LA CEIBA,ROATAN,TELA,BALFATE,YORO,LA ESPERANZA,CAYETANO,EL GUINEO,AZACUALPA-PATUCA,SANTA MARIA,CATACAMAS,MANTO,EL VIJAO,LA LIMA,TEGUCIGALPA,SANTA LUCIA,LA VENTA,GUINOPE,SAN ANTONIO DE FLORES,SAN LUCAS,TEXIGUAT,AMAPALA,ALIANZA,CHOLUTECA,EL CEDRITO,GOASCORAN,LIURE,NAMASIGUE,SABANA GRANDE,LA LABOR,LA MESA,POTRERILLOS,SAN FELIPE
0,Lat,14.741389,14.466667,14.910,14.423611,14.29104,14.775000,14.892778,14.775775,14.771667,14.813889,14.692222,15.194722,15.06359,15.34732,15.739167,16.317708,15.769139,15.78049,15.12479,14.29361,14.461111,14.55929,14.436667,14.145833,14.838114,14.920556,14.450556,14.555278,14.059028,14.119028,14.33767,13.88221,13.72119,13.74147,13.65013,13.29433,13.51226,13.239000,13.10650,13.61040,13.532307,13.206945,13.82017,14.48745,15.449111,15.22986,14.208056
1,Lon,-87.369444,-87.068056,-87.265,-87.701667,-87.57040,-88.011667,-87.920833,-88.774443,-88.338056,-88.404444,-88.356389,-87.874167,-88.74608,-88.40522,-86.860000,-86.529354,-87.530056,-86.37883,-87.13358,-88.17250,-86.014167,-86.11024,-86.110000,-86.242500,-85.874675,-86.071944,-86.075278,-86.111667,-87.220056,-87.120056,-87.16840,-86.93582,-86.88186,-86.95544,-87.02421,-87.65322,-87.72474,-87.160056,-87.06519,-87.75423,-87.087661,-87.132728,-87.25393,-88.99484,-87.940056,-87.96399,-86.132222
2,1980-01-01 00:00:00,0.700000,0.000000,0.000,0.000000,0.00000,0.000000,6.800000,5.200000,2.800000,0.000000,0.000000,5.700000,6.40000,2.30000,0.200000,NaN,29.000000,NaN,NaN,NaN,NaN,0.00000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.00000,0.00000,0.00000,0.00000,0.00000,NaN,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,5.100000,0.00000,0.000000
3,1980-01-02 00:00:00,0.000000,0.000000,0.000,0.000000,0.00000,0.000000,0.400000,3.900000,0.000000,0.000000,3.700000,0.000000,0.10000,0.00000,4.600000,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.00000,0.00000,0.00000,0.00000,0.00000,NaN,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.300000,0.00000,0.000000
4,1980-01-03 00:00:00,0.000000,0.000000,0.000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.300000,0.000000,0.000000,0.00000,0.00000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.200000,1.500000,0.500000,0.000000,0.100000,0.000000,0.000000,NaN,0.00000,0.00000,0.00000,0.00000,0.00000,NaN,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14973,2020-12-27 00:00:00,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,149.000000,0.000000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN
14974,2020-12-28 00:00:00,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,17.300000,16.200000,0.00000,3.20000,0.00000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN
14975,2020-12-29 00:00:00,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,8.800000,3.600000,1.30000,0.00000,0.00000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN
14976,2020-12-30 00:00:00,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,18.000000,0.000000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN
14977,2020-12-31 00:00:00,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,14.000000,0.000000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN,8.400000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN

In [4]:
estaciones = precipitacion.iloc[:2].T
estaciones.columns = estaciones.iloc[0]
estaciones = estaciones.iloc[1:]
#save
#estaciones.to_csv('coordinates_prec.csv')
precipitacion = precipitacion.iloc[2:].reset_index(drop=True)
precipitacion.rename(
    columns={'ESTACION':'date'},
    inplace=True
)
precipitacion['date'] = pd.to_datetime(
    precipitacion['date']
)

In [5]:
precipitacion.set_index('date', inplace=True)

# quality control

In [6]:
precipitacion[precipitacion['LA CEIBA']>450]

,ESQUIAS,LA ERMITA,SULACO,PLAYITAS,FLORES,PITO SOLO,SANTA ELENA,SANTA ROSA DE COPAN,EL NISPERO,LA UNION,SAN JOSE DE LA MONTAÃ‘A,SANTA RITA,LA ENTRADA,QUIMISTA,LA CEIBA,ROATAN,TELA,BALFATE,YORO,LA ESPERANZA,CAYETANO,EL GUINEO,AZACUALPA-PATUCA,SANTA MARIA,CATACAMAS,MANTO,EL VIJAO,LA LIMA,TEGUCIGALPA,SANTA LUCIA,LA VENTA,GUINOPE,SAN ANTONIO DE FLORES,SAN LUCAS,TEXIGUAT,AMAPALA,ALIANZA,CHOLUTECA,EL CEDRITO,GOASCORAN,LIURE,NAMASIGUE,SABANA GRANDE,LA LABOR,LA MESA,POTRERILLOS,SAN FELIPE
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1993-10-31,6.7,1.0,11.3,0.0,3.6,53.9,48.1,10.7,20.2,25.4,21.5,NaN,8.1,36.6,551.0,37.0,203.9,239.6,83.8,14.40,6.2,0.0,1.4,NaN,0.0,3.7,7.2,0.0,9.30,0.0,1.7,0.3,0.0,16.2,3.2,0.9,0.0,0.8,18.9,0.0,0.0,3.2,0.0,10.1,51.0,22.5,2.2
2013-11-28,NaN,0.2,NaN,0.0,0.0,NaN,NaN,7.9,NaN,NaN,NaN,NaN,0.1,0.0,497.6,164.8,139.5,126.1,19.6,0.01,NaN,NaN,4.2,NaN,0.0,NaN,NaN,NaN,6.71,0.8,NaN,0.0,0.0,0.0,NaN,0.0,0.0,1.5,0.0,0.0,0.0,NaN,0.0,0.8,8.2,2.0,NaN

In [7]:
# algunas estaciones estaban con -9999.999 se le asigna nan
precipitacion=precipitacion.applymap(lambda x: np.nan if x < 0 else x)
# como un control de calidad se limitará a 450
precipitacion=precipitacion.applymap(lambda x: np.nan if x > 450 else x)

# Outputs

In [8]:
def count_days_greater_than_limit(x, limit):
    if x.dropna().size / x.size >= 0.95:
        return (x > limit).sum()
    else:
        return np.nan

In [9]:
grouper = pd.Grouper(freq='M')

In [12]:
precipitacion.groupby(grouper).agg(lambda x: count_days_greater_than_limit(x, 10)).to_csv('Z:\\1.Data\\Honduras\\transformed\\monthly_agg\\obs_stations_r10mm_monthly.csv')

In [13]:
precipitacion.groupby(grouper).agg(lambda x: count_days_greater_than_limit(x, 15)).to_csv('Z:\\1.Data\\Honduras\\transformed\\monthly_agg\\obs_stations_r15mm_monthly.csv')